### PR TITLE
Enable Support for Progressive Web Applications (PWA)

### LINKED ISSUE #21: Enable PWA Support
We should enable PWA (Progressive Web Application) support for this web application. This can be easily done by un-commenting the following section in `index.html`

https://github.com/OpenArchitex/AccoTech/blob/46ba0b06a922f780ae3c44912f188644415120ee/src/main/webapp/index.html#L84-L94

We can test this using [Chrome's LightHouse tools](https://developers.google.com/web/tools/lighthouse/)

### PR DESCRIPTION
**Pull request by DevanshCodes**
Resolves #21

### CODE REVIEW

**Comment by DevanshCodes** [comment]
Okay sure will do ASAP. Sorry for trouble I think I'm using ESlint which caused the issue.

**Comment by SudharakaP** [comment]
> Okay sure will do ASAP. Sorry for trouble I think I'm using ESlint which caused the issue.

@DevanshCodes : Don't worry, it's not a trouble. thanks for contributing. All you need to do is a simple rebase and we are good I think. 👍🏼

**Comment by DevanshCodes** [comment]
Hey @SudharakaP Can you check it now?

**Comment by SudharakaP** [comment]
> Hey @SudharakaP Can you check it now?

There's still unnecessary formatting and it seems that you haven't re-based from master; https://github.com/OpenArchitex/AccoTech/pull/22/files. One other easy method you could do this is run `prettier --write "{,src/**/}*.{md,json,ts,tsx,css,scss,yml,html}"` within the project folder which will reformat everything for you. Then you will be left with the actual changes you did without the formatting.

**Comment by DevanshCodes** [comment]
> > Hey @SudharakaP Can you check it now?
> 
> There's still unnecessary formatting and it seems that you haven't re-based from master; https://github.com/OpenArchitex/AccoTech/pull/22/files. One other easy method you could do this is run `prettier --write "{,src/**/}*.{md,json,ts,tsx,css,scss,yml,html}"` within the project folder which will reformat everything for you. Then you will be left with the actual changes you did without the formatting.

Done the same and pushed. Let me know if its okay or not.

**Comment by SudharakaP** [comment]
@DevanshCodes : It's better but not quite. For some reason still you have other formatting changes included in your PR; https://github.com/OpenArchitex/AccoTech/pull/22/files. But that's okay. I am going to merge this and I'll fix it afterwards. Thanks much for the contribution. 👍🏼

**Comment by SudharakaP** [comment]
@DevanshCodes : Thanks much for the contribution. Feel free to pick any other unassigned issues in the repo if you feel like it. 😄

**Pull request merged**
